# Default Configuration for Drift Gym Environment

# Environment Settings
environment:
  max_steps: 400
  dt: 0.05  # Simulation timestep (seconds)
  seed: null  # Random seed for reproducibility

# Vehicle Physical Parameters
vehicle:
  mass: 1.5  # kg (F1/10 scale)
  wheelbase: 0.25  # meters (l_f + l_r)
  l_f: 0.125  # Front axle to CoM (meters)
  l_r: 0.125  # Rear axle to CoM (meters)
  width: 0.19  # Vehicle width (meters)
  max_steering_angle: 0.785  # rad (45 degrees)
  
  # Control Limits
  max_velocity: 4.2  # m/s (measured from hardware)
  max_acceleration: 3.0  # m/s^2
  max_angular_velocity: 3.5  # rad/s

# Pacejka Tire Model Parameters (Magic Formula)
tire:
  use_pacejka: true  # Use realistic tire model vs simple kinematic
  
  # Longitudinal force coefficients
  B_x: 10.0  # Stiffness factor
  C_x: 1.9   # Shape factor
  D_x: 1.0   # Peak factor
  E_x: 0.97  # Curvature factor
  
  # Lateral force coefficients
  B_y: 8.0
  C_y: 1.3
  D_y: 1.0
  E_y: -1.6
  
  # Combined slip
  mu_peak: 1.0  # Peak friction coefficient
  mu_slide: 0.7  # Sliding friction coefficient

# Reward Function Weights
rewards:
  # Progress rewards (positive)
  gate_pass_bonus: 100.0
  progress_reward_scale: 5.0
  speed_reward_scale: 0.5
  
  # Drift-specific rewards
  drift_angle_reward: 2.0  # Reward for controlled slip
  drift_speed_bonus: 1.0   # Bonus for drifting at high speed
  optimal_slip_angle: 0.2  # Target slip angle (rad)
  slip_angle_tolerance: 0.15
  
  # Penalties (negative)
  collision_penalty: -100.0
  boundary_penalty: -50.0
  lateral_error_scale: -1.5
  angle_error_scale: -0.8
  control_effort_scale: -0.01
  time_penalty: -0.05
  
  # Reward clipping
  clip_rewards: true
  reward_min: -10.0
  reward_max: 10.0

# Observation Space Configuration
observation:
  normalize: true
  include_velocity: true
  include_angular_velocity: true
  include_position: true
  include_heading: true  # as cos/sin
  include_gate_info: true
  include_obstacles: true
  include_slip_angle: true
  include_acceleration: true
  history_length: 1  # Number of past observations to stack

# Action Space Configuration
action:
  type: "high_level"  # "high_level" [v, Ï‰] or "low_level" [steering, throttle, brake]
  normalize: true

# Scenario Configuration
scenarios:
  # Predefined scenarios
  loose:
    gate_width: 2.13
    gate_position: [3.0, 1.065]
    num_obstacles: 2
    obstacle_radius_range: [0.3, 0.5]
    
  tight:
    gate_width: 0.81
    gate_position: [3.0, 0.405]
    num_obstacles: 3
    obstacle_radius_range: [0.25, 0.4]
  
  slalom:
    num_gates: 5
    gate_spacing: 2.0
    gate_width: 1.5
    offset_range: [-1.0, 1.0]
  
  # Randomization settings
  randomization:
    enabled: true
    randomize_gate_position: true
    position_noise: 0.2  # meters
    randomize_gate_width: true
    width_range: [0.8, 2.5]  # meters
    randomize_obstacles: true
    num_obstacles_range: [2, 6]
    randomize_start_position: true
    start_position_noise: 0.5  # meters
    randomize_start_velocity: true
    start_velocity_range: [0.0, 2.0]  # m/s

# Domain Randomization (for sim-to-real transfer)
domain_randomization:
  enabled: false  # Enable for robust policies
  
  # Physics randomization
  mass_range: [1.2, 1.8]
  friction_range: [0.6, 1.2]
  
  # Sensing delays and noise
  imu_delay_range: [0.0, 0.1]  # seconds
  imu_noise_std: 0.02
  
  # Control delays
  actuation_delay_range: [0.0, 0.05]  # seconds
  
  # Environmental
  wind_force_range: [0.0, 0.5]  # N
  surface_irregularity: 0.1

# Curriculum Learning
curriculum:
  enabled: false
  
  # Difficulty levels (0 = easiest, 10 = hardest)
  start_level: 0
  max_level: 10
  
  # Progression criteria
  success_rate_threshold: 0.75  # Move to next level at 75% success
  evaluation_episodes: 20  # Episodes to evaluate success rate
  
  # Level parameters (linearly interpolated)
  level_0:
    gate_width: 2.5
    num_obstacles: 1
    max_velocity: 3.0
  
  level_10:
    gate_width: 0.6
    num_obstacles: 8
    max_velocity: 4.2

# Rendering Settings
rendering:
  mode: "rgb_array"  # "human", "rgb_array", or null
  window_size: 800
  fps: 30
  scale: 60  # pixels per meter
  
  # Rendering optimizations
  cache_static_elements: true
  render_trajectory: true
  max_trajectory_points: 200
  
  # Colors (RGB)
  background: [240, 240, 240]
  grid: [220, 220, 220]
  vehicle: [50, 50, 200]
  trajectory: [100, 150, 255]
  obstacle: [200, 100, 100]
  gate: [50, 200, 50]

# Logging and Debugging
logging:
  log_episodes: false
  log_dir: "./logs"
  save_trajectories: false
  verbose: 0  # 0=none, 1=info, 2=debug
